apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: backstage-role
rules:
- apiGroups: [""]  # "" indicates the core API group
  resources: ["pods", "deployments"]
  verbs: ["get", "list", "watch"]
