apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backstage-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: backstage-sa
  namespace: default
roleRef:
  kind: Role
  name: backstage-role
  apiGroup: rbac.authorization.k8s.io
