apiVersion: apps/v1
kind: Deployment
metadata:
  name: juliet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juliet
  template:
    metadata:
      labels:
        app: juliet
    spec:
      containers:
      - name: juliet
        image: juliet:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
