apiVersion: v1
kind: Service
metadata:
  name: juliet
spec:
  selector:
    app: juliet
  ports:
    - protocol: TCP
      port: 8080 # This is the service port inside Kubernetes
      targetPort: 8000 # This is the port exposed by the container
      nodePort: 31005
  type: NodePort
